# Generated by Django 4.0.4 on 2022-07-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.IntegerField(verbose_name='tg_chat_id')),
                ('telegram_user_id', models.IntegerField(verbose_name='tg_user_id')),
            ],
            options={
                'verbose_name': 'Telegram Пользователь',
                'verbose_name_plural': 'Telegram Пользователи',
                'ordering': ('id',),
            },
        ),
    ]
