# Generated by Django 4.0.4 on 2022-06-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='description',
            field=models.CharField(default='Unknown', max_length=255, verbose_name='Описание'),
        ),
    ]
