# Generated by Django 4.0.4 on 2022-06-14 07:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_goalcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalcomment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 7, 58, 51, 396144, tzinfo=utc), verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='goalcomment',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 7, 58, 51, 396144, tzinfo=utc), verbose_name='Дата последнего обновления'),
        ),
    ]
