# Generated by Django 4.0.4 on 2022-06-14 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_goalcomment_created_goalcomment_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalcomment',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='goalcomment',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата последнего обновления'),
        ),
    ]
