# Generated by Django 4.0.4 on 2022-06-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_alter_goalcomment_created_alter_goalcomment_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalcomment',
            name='created',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='goalcomment',
            name='updated',
            field=models.DateTimeField(verbose_name='Дата последнего обновления'),
        ),
    ]
