# Generated by Django 4.0.4 on 2022-06-26 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0013_alter_goal_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='due_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата дедлайна'),
        ),
    ]
