version: "3.9"
services:
  db:
    container_name: calendar_postgres
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: djangoappuserdb
      POSTGRES_PASSWORD: djangoappuserdb
      POSTGRES_DB: calendar
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d calendar -U djangoappuserdb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data: