tg_test_data = {'ok': True,
                'result': [{'message': {'chat': {'first_name': 'Daniil',
                                                 'id': 220018112,
                                                 'type': 'private',
                                                 'username': 'DanielPython'},
                                        'date': 1656574262,
                                        'entities': [{'length': 6,
                                                      'offset': 0,
                                                      'type': 'bot_command'}],
                                        'from': {'first_name': 'Daniil',
                                                 'id': 220018112,
                                                 'is_bot': False,
                                                 'language_code': 'ru',
                                                 'username': 'DanielPython'},
                                        'message_id': 1,
                                        'text': '/start'},
                            'update_id': 108838499},
                           {'message': {'chat': {'first_name': 'Daniil',
                                                 'id': 220018112,
                                                 'type': 'private',
                                                 'username': 'DanielPython'},
                                        'date': 1656574270,
                                        'from': {'first_name': 'Daniil',
                                                 'id': 220018112,
                                                 'is_bot': False,
                                                 'language_code': 'ru',
                                                 'username': 'DanielPython'},
                                        'message_id': 2,
                                        'text': 'Hello'},
                            'update_id': 108838500}]
                }

test_sendMessage_data = {'ok': True,
                         'result': {'chat': {'first_name': 'Daniil',
                                             'id': 220018112,
                                             'type': 'private',
                                             'username': 'DanielPython'},
                                    'date': 1656589088,
                                    'from': {'first_name': 'MyAppBot',
                                             'id': 5418285199,
                                             'is_bot': True,
                                             'username': 'goalboardpart_bot'},
                                    'message_id': 5,
                                    'text': 'Привет Анютовскинс'}}
