name: Build and deploy action
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - '**/tests/**'
env:
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_NAME: ${{ secrets.DB_NAME }}
  NAME_APP: ${{secrets.NAME_APP}}
  VK_OAUTH2_KEY : ${{secrets.VK_OAUTH2_KEY}}
  VK_OAUTH2_SECRET : ${{secrets.VK_OAUTH2_SECRET}}
  TELEGRAM_TOKEN_BOT: ${{secrets.TELEGRAM_TOKEN_BOT}}


jobs:
  testssss:
    runs-on: ubuntu-latest
    env:
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
    steps:
      - name: run docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: $SSH_USERNAME
          password: $SSH_PASSWORD
          script: |
            echo homepath $HOME
            cd ${{secrets.NAME_APP}}
            echo ${{ SSH_USERNAME }}
            echo $SSH_PASSWORD