name: Build and deploy action
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - '**/tests/**'
      - '**action.yaml'
env:
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_NAME: ${{ secrets.DB_NAME }}
  SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
  NAME_APP: ${{secrets.NAME_APP}}
  VK_OAUTH2_KEY : ${{secrets.VK_OAUTH2_KEY}}
  VK_OAUTH2_SECRET : ${{secrets.VK_OAUTH2_SECRET}}


jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: Echo gitHubname and repo
        run: echo ${{ github.repository }}/${{ github.ref_name }}/${{secrets.NAME_APP}}
      - name: 'render .env file'
        run: |
          cat ci.env | envsubst > myappcalendar/.env